name: filipino_cuisine
description: A Flutter app that shows list of Filipino Food, it shows the recipe and instructions..
version: 1.0.0
author: John Mark Grancapal <mark.grancapal@gmail.com>
homepage: https://github.com/markgrancapal

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_swiper: ^1.1.6
  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/fc_icon.png"

flutter:
  uses-material-design: true

  assets:
    - calamares.jpg
    - beef_caldereta.jpg
    - pochero.jpg
    - pork_sisig.jpg
    - embutido.jpg
    - black_pepper.png
    - butter.png
    - chili.png
    - egg.png
    - flour.png
    - garlic.png
    - lemon.png
    - oil.png
    - onion.png
    - pork.png
    - salt.png
    - squid.png
    - tomato.png
    - banana.png
    - cabbage.png
    - bokchoy.png
    - green_beans.png
    - potato.png
    - red_pepper.png
    - yellow_onion.png
    - red_bell.png
    - green_bell.png
    - carrot.png
    - beef.png
    - cheese.png
    - raisins.png
    - ground_pork.png
    - sausage.png

  fonts:
    - family: opr
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
    - family: opb
      fonts:
        - asset: fonts/OpenSans-Bold.ttf
    - family: ark
      fonts:
        - asset: fonts/Arkipelago.otf